#!/usr/bin/python2.7
from hosted import device, node, config
config.restart_on_update()

counter = 0
device.gpio.monitor(config.pin2)
for (pin2, state) in device.gpio.poll_forever():
    if state is True:
        counter += 10
        node.send('/counter:%d' % counter)


