#!/usr/bin/python2.7
from hosted import device, node, config
config.restart_on_update()

counter = 0
 

device.gpio.monitor(config.pin)
device.gpio.monitor(config.pin2)
for (pin, state) in device.gpio.poll_forever():
    
    if state is True:
    if pin=18 then counter += 10
    if pin=17 then counter += 1 
        node.send('/counter:%d' % counter)
        

            

