#!/usr/bin/python2.7
from hosted import device, node, config
config.restart_on_update()

counter = 0
pins = set()
pins.add(18)
pins.add(17)

print >>sys.stderr, "gpios active: %s" % (pins,)
    for pin in pins:
        device.gpio.monitor(pin)
    for pin, high in device.gpio.poll_forever():
        if high:
        counter += 10
        node.send('/counter:%d' % counter)
            

